import { getSession } from "@/lib/auth/session";
import { redirect } from "next/navigation";
import QuoteHistoryTable from "@/app/calculator/_components/QuoteHistoryTable";

export default function AdminHistoryPage() {
  const session = getSession();
  const role = session?.isAdmin ? "admin" : session?.modules?.calculator;
  if (!session || !role) redirect("/login");
  if (role !== "admin") redirect("/calculator/client");
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <div className="max-w-6xl mx-auto px-4 pb-10">
        <h1 className="text-2xl font-bold text-gray-900 mb-1 dark:text-white">Quote History</h1>
        <p className="text-sm text-gray-500 mb-6 dark:text-gray-400">All quotes generated by admin and clients.</p>
        <QuoteHistoryTable showClientColumn />
      </div>
    </div>
  );
}
